### DISCUSSION TITLE
Mermaid style for Design Review presentation

### DISCUSSION THREAD

**Discussion by dyc3** [dyc3/sys-581-group-project#32] [General]
paste at very top of diagram

```
---
config:
  theme: base
  themeVariables:
    darkMode: true
    background: "#001633"
    primaryColor: "#001633"
    primaryTextColor: "#fff"
    primaryBorderColor: "#69cbcf"
    lineColor: "#ffab40"
    activationBkgColor: "#001633"
    activationBorderColor: "#ffab40"
    actorLineColor: "#69cbcf"
    signalColor: "#69cbcf"
    noteBkgColor: "#001633"
    noteTextColor: "#fff"
    noteBorderColor: "#ffab40"
---
```

example:
```mermaid
---
config:
  theme: base
  themeVariables:
    darkMode: true
    background: "#001633"
    primaryColor: "#001633"
    primaryTextColor: "#fff"
    primaryBorderColor: "#69cbcf"
    lineColor: "#ffab40"
    activationBkgColor: "#001633"
    activationBorderColor: "#ffab40"
    actorLineColor: "#69cbcf"
    signalColor: "#69cbcf"
    noteBkgColor: "#001633"
    noteTextColor: "#fff"
    noteBorderColor: "#ffab40"
---
sequenceDiagram
    Alice->>+John: Hello John, how are you?
    Alice->>+John: John, can you hear me?
    John-->>-Alice: Hi Alice, I can hear you!
    John-->>-Alice: I feel great!
```
